### ISSUE TITLE
Update Vagrant/VirtualBox

### ISSUE THREAD

**Issue by lynnaloo** [lynnaloo/golang-vagrant#2]
Update Vagrant and VirtualBox to the latest versions.

**Comment by IngCr3at1on** [comment]
@lynnaloo are you referring to just the readme versions shown (and links)?

**Comment by lynnaloo** [comment]
That and making changes to the `Vagrantfile` if necessary. It's possible some things have been deprecated or changed since the version referenced in the README.md.
